version: "3.7"

services:
  gateway:
    container_name: ceus-gateway
    image: 100538092962.dkr.ecr.us-east-1.amazonaws.com/ceus/api-gateway:live
    restart: always
    ports:
      - 80:8080
    environment:
      MICROSERVICE_USER_API_URL: http://ceus-users:8000
      MICROSERVICE_TRANSACTION_API_URL: http://ceus-transactions:8000
      MICROSERVICE_DATA_API_URL: http://ceus-data:8000
      AWS_REGION_NAME: us-east-1
  users:
    container_name: ceus-users
    image: 100538092962.dkr.ecr.us-east-1.amazonaws.com/ceus/ms-user:live
    restart: always
    ports:
      - 8000
    env_file: users.env
  transaction:
    container_name: ceus-transactions
    image: 100538092962.dkr.ecr.us-east-1.amazonaws.com/ceus/ms-transaction:live
    restart: always
    ports:
      - 8000
    env_file: transactions.env
  transaction_celery:
    container_name: ceus-transactions-celery
    image: 100538092962.dkr.ecr.us-east-1.amazonaws.com/ceus/ms-transaction:live
    command: celery -A apps.utils worker -l info
    depends_on:
      - transaction
    restart: always
    ports:
      - 8000
    env_file: transactions.env
  transaction_celery_beat:
    container_name: ceus-transactions-celery-beat
    image: 100538092962.dkr.ecr.us-east-1.amazonaws.com/ceus/ms-transaction:live
    command: celery -A apps.utils beat -l info
    depends_on:
      - transaction
    restart: always
    ports:
      - 8000
    env_file: transactions.env
  data:
    container_name: ceus-data
    image: 100538092962.dkr.ecr.us-east-1.amazonaws.com/ceus/ms-data:live
    restart: always
    ports:
      - 8000
    env_file: data.env
